line-length = 120
include = ["src/**/*.(py|pyi)", "tests/**/*.(py|pyi)", "pyproject.toml"]

[lint]
select = ["D102", "F401"]

[lint.isort]
case-sensitive = true
relative-imports-order = "closest-to-furthest"

[lint.extend-per-file-ignores]
"tests/**/*.py" = ["D102"]

[format]
quote-style = "double"
indent-style = "space"
